alertmanager:
  config:
    route:
      receiver: telegram

    receivers:
      - name: telegram
        telegram_configs:
          - bot_token: "REPLACE_ME"
            chat_id: 123456789
            parse_mode: HTML
            message: |
              🚨 ALERT 🚨

              Alert: {{ .CommonLabels.alertname }}
              Severity: {{ .CommonLabels.severity }}

              {{ .CommonAnnotations.summary }}

              {{ .CommonAnnotations.description }}
