apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-demo-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sre-demo-app
  template:
    metadata:
      labels:
        app: sre-demo-app
    spec:
      containers:
      - name: sre-demo-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Never

        ports:
        - containerPort: 8000

        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: sre-demo-config
              key: APP_ENV

        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: sre-demo-config
              key: LOG_LEVEL

        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: sre-demo-config
              key: APP_VERSION

        - name: DEMO_SECRET
          valueFrom:
            secretKeyRef:
              name: sre-demo-secret
              key: DEMO_SECRET

        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}