apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sre-demo-servicemonitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: sre-demo-app

  endpoints:
    - port: http
      path: /metrics
      interval: 15s

  namespaceSelector:
    matchNames:
      - sre-demo